#include "MCStatistics.hpp"
#include <vector>
using std::vector;

MCStatisticsMean::MCStatisticsMean() : runningSum(0.0), pathsDone(0UL) {
    
}

void MCStatisticsMean::dumpOneResult(double result) {
    pathsDone++;
    runningSum += result;
}

std::vector<std::vector<double>> MCStatisticsMean::getResultsSoFar() const {
    vector<vector<double>> results(1);
    
    results[0].resize(1);
    results[0][0] = runningSum / pathsDone;
    
    return results;
}

MCStatistics* MCStatisticsMean::clone() const {
    return new MCStatisticsMean(*this); // use copy constructor generated by compiler
}
